Fix: Correctly name macOS package artifact

diff --git a/.github/scripts/package-macos b/.github/scripts/package-macos
--- a/.github/scripts/package-macos
+++ b/.github/scripts/package-macos
@@ -55,6 +55,7 @@ package() {
 
   local config='RelWithDebInfo'
   local -r -a _valid_configs=(Debug RelWithDebInfo Release MinSizeRel)
+  local target='macos-universal'
 
   local -i codesign=0
   local -i notarize=0
@@ -69,6 +70,12 @@ package() {
           exit 2
         }
         ;;
+      -t|--target)
+        if (( # == 1 )) || [[ ${2:0:1} == '-' ]] {
+          log_error "Missing value for option %B${1}%b"
+          exit 2
+        }
+        ;;
     }
     case ${1} {
       --) shift; args+=($@); break ;;
@@ -78,6 +85,10 @@ package() {
           exit 2
         }
         config=${2}
+        shift 2
+        ;;
+      -t|--target)
+        target=${2}
         shift 2
         ;;
       -s|--codesign) typeset -g codesign=1; shift ;;
@@ -97,7 +108,7 @@ package() {
   read -r product_name product_version <<< \
     "$(jq -r '. | {name, version} | join(" ")' ${buildspec_file})"
 
-  local output_name="${product_name}-${product_version}-${host_os}-universal"
+  local output_name="${product_name}-${product_version}-${target}"
 
   if [[ ! -d ${project_root}/release/${config}/${product_name}.plugin ]] {
     log_error 'No release artifact found. Run the build script or the CMake install procedure first.'
